//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplainClient {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplainClient.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إضافة شكوى.
        /// </summary>
        public static string AddComplaints {
            get {
                return ResourceManager.GetString("AddComplaints", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مضمون الشكوى.
        /// </summary>
        public static string ComplainBody {
            get {
                return ResourceManager.GetString("ComplainBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تاريخ الشكوى.
        /// </summary>
        public static string ComplainDateTime {
            get {
                return ResourceManager.GetString("ComplainDateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الشكوى غير صحيح.
        /// </summary>
        public static string ComplainIdErrorMessage {
            get {
                return ResourceManager.GetString("ComplainIdErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بيانات الشكوى.
        /// </summary>
        public static string ComplainInfo {
            get {
                return ResourceManager.GetString("ComplainInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرد على الشكوى.
        /// </summary>
        public static string ComplainReply {
            get {
                return ResourceManager.GetString("ComplainReply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الشكوى الخاصة ب .
        /// </summary>
        public static string ComplainSaveMessage {
            get {
                return ResourceManager.GetString("ComplainSaveMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الشكوى بنجاح.
        /// </summary>
        public static string ComplainSaveMessageTitle {
            get {
                return ResourceManager.GetString("ComplainSaveMessageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حالة الشكوى.
        /// </summary>
        public static string ComplainStatus {
            get {
                return ResourceManager.GetString("ComplainStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شكوى/التماس.
        /// </summary>
        public static string ComplainType {
            get {
                return ResourceManager.GetString("ComplainType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوحدة المتمركز بها.
        /// </summary>
        public static string CurrentUnit {
            get {
                return ResourceManager.GetString("CurrentUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تحميل.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكن أن يتعدى حجم الملف 5 ميجا بايت.
        /// </summary>
        public static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الشكوى.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  الاستعلام عن شكوى.
        /// </summary>
        public static string InquireAboutComplain {
            get {
                return ResourceManager.GetString("InquireAboutComplain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to للإستعلام عن الشكوى يرجي الضغط على الرئيسية / استعلام عن شكوى ثم ادخال بيانات الشكوى المذكورة اعلاه .
        /// </summary>
        public static string InquireAboutComplainHelp {
            get {
                return ResourceManager.GetString("InquireAboutComplainHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عنوان الشبكة المحلية.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرقم العسكري.
        /// </summary>
        public static string MilitaryNumber {
            get {
                return ResourceManager.GetString("MilitaryNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرقم العسكري يجب ان يكون من 4 الى 20 رقم.
        /// </summary>
        public static string MilitaryNumberValidationMessage {
            get {
                return ResourceManager.GetString("MilitaryNumberValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الإسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون الاسم من 10 إلى 100 حرف.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الوحدة الأساسية.
        /// </summary>
        public static string NativeUnit {
            get {
                return ResourceManager.GetString("NativeUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يوجد شكوى بالبيانات المطلوبة.
        /// </summary>
        public static string NoEntityWasFound {
            get {
                return ResourceManager.GetString("NoEntityWasFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لم يتم الرد.
        /// </summary>
        public static string NoReply {
            get {
                return ResourceManager.GetString("NoReply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to البيانات الشخصية.
        /// </summary>
        public static string PersonalInfo {
            get {
                return ResourceManager.GetString("PersonalInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string PhoneNumberOne {
            get {
                return ResourceManager.GetString("PhoneNumberOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الهاتف 2.
        /// </summary>
        public static string PhoneNumberTwo {
            get {
                return ResourceManager.GetString("PhoneNumberTwo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to منظومة الشكاوي.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to منظومة شكاوي القوات الجوية.
        /// </summary>
        public static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رتبة/درجة.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الشكاوى المسجلة.
        /// </summary>
        public static string RecordedComplains {
            get {
                return ResourceManager.GetString("RecordedComplains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جاري تسجيل الشكوى ...
        /// </summary>
        public static string RecordingComplains {
            get {
                return ResourceManager.GetString("RecordingComplains", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرد.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        public static string ReturnHome {
            get {
                return ResourceManager.GetString("ReturnHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عفواٌ , هذا الرابط غير موجود.
        /// </summary>
        public static string RouteIsNotConfigured {
            get {
                return ResourceManager.GetString("RouteIsNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to جاري البحث.
        /// </summary>
        public static string SearchOngoing {
            get {
                return ResourceManager.GetString("SearchOngoing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الهاتف الثانوي.
        /// </summary>
        public static string SecondaryPhoneNumber {
            get {
                return ResourceManager.GetString("SecondaryPhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرقم القومي.
        /// </summary>
        public static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب أن يتكون الرقم القومي من 14 رقم.
        /// </summary>
        public static string SSNLength {
            get {
                return ResourceManager.GetString("SSNLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الرقم القومي يجب ان يكون من 14 رقم.
        /// </summary>
        public static string SSNValidationMessage {
            get {
                return ResourceManager.GetString("SSNValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عنوان الشكوى.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to بيانات الوحدة.
        /// </summary>
        public static string UnitInfo {
            get {
                return ResourceManager.GetString("UnitInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسم :.
        /// </summary>
        public static string WithName {
            get {
                return ResourceManager.GetString("WithName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رتبة / درجة :.
        /// </summary>
        public static string WithRank {
            get {
                return ResourceManager.GetString("WithRank", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم قومي :.
        /// </summary>
        public static string WithSSN {
            get {
                return ResourceManager.GetString("WithSSN", resourceCulture);
            }
        }
        public static string ToDepartementPresidentMesssage
        {
            get {
                return ResourceManager.GetString("ToDepartementPresidentMesssage", resourceCulture);
            }
        }
        public static string AppliedToYouMessage
        {
            get {
                return ResourceManager.GetString("AppliedToYouMessage", resourceCulture);
            }
        }
        public static string FromNativeUnitOf
        {
            get {
                return ResourceManager.GetString("FromNativeUnitOf", resourceCulture);
            }
        }
        public static string FromCurrentUnitOf
        {
            get {
                return ResourceManager.GetString("FromCurrentUnitOf", resourceCulture);
            }
        }
        public static string SubjectOfComplainTemplate
        {
            get {
                return ResourceManager.GetString("SubjectOfComplainTemplate", resourceCulture);
            }
        }
        public static string ComplainRequest
        {
            get {
                return ResourceManager.GetString("ComplainRequest", resourceCulture);
            }
        }
        public static string Complain
        {
            get {
                return ResourceManager.GetString("Complain", resourceCulture);
            }
        }
    }
}
